version: '3.4'

networks:
  dev_net:
    name: dev_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
  
services:
  worker:
    image: ${DOCKER_REGISTRY-}worker
    networks:
      dev_net:
        ipv4_address: "10.10.0.4"
    build:
      context: Worker
      dockerfile: Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    networks:
      dev_net:
        ipv4_address: "10.10.0.5"
    ports:
    - "4040:4040"
    build:
      context: .
      dockerfile: WebAPI/Dockerfile